import AVFoundation
import os

/// Named sound cues, decoupled from their files.
///
/// Every cue is a slot: swapping `caught.wav` for recorded or commissioned audio
/// is a file replacement with no code change anywhere. The bundled set is
/// generated by `tools/make_sfx.py` as original 8-bit-style synthesis, so the
/// app owns its audio outright.
enum SoundCue: String, CaseIterable {
    case select, back, error
    case orbSpin = "orb_spin"
    case dexOpen = "dex_open"
    case dexClose = "dex_close"
    case detect, throwOrb = "throw", shake, escape
    case caught, registered, duplicate
    case fanfareUncommon = "fanfare_uncommon"
    case fanfareRare = "fanfare_rare"
    case fanfareEpic = "fanfare_epic"
    case fanfareLegendary = "fanfare_legendary"

    /// The fanfare a given tier resolves to. Common catches get no fanfare —
    /// if everything is celebrated, nothing is.
    static func fanfare(for rarity: Rarity) -> SoundCue? {
        switch rarity {
        case .common:    return nil
        case .uncommon:  return .fanfareUncommon
        case .rare:      return .fanfareRare
        case .epic:      return .fanfareEpic
        case .legendary: return .fanfareLegendary
        }
    }
}

@MainActor
final class SoundBank {
    static let shared = SoundBank()

    var isMuted = false

    /// Players are retained per cue and rewound rather than reallocated —
    /// building an AVAudioPlayer costs enough to be audible as latency on a
    /// cue that should fire the instant you tap.
    private var players: [SoundCue: AVAudioPlayer] = [:]
    private let log = Logger(subsystem: "com.abhay.animaldex", category: "audio")

    private init() {
        configureSession()
    }

    private func configureSession() {
        do {
            // .ambient so the app never interrupts the user's music — a game you
            // play outdoors should not stop someone's podcast.
            try AVAudioSession.sharedInstance().setCategory(.ambient, mode: .default)
            try AVAudioSession.sharedInstance().setActive(true)
        } catch {
            log.error("audio session: \(error.localizedDescription)")
        }
    }

    func preload() {
        for cue in SoundCue.allCases { _ = player(for: cue) }
    }

    private func player(for cue: SoundCue) -> AVAudioPlayer? {
        if let existing = players[cue] { return existing }
        guard let url = Bundle.main.url(forResource: cue.rawValue, withExtension: "wav") else {
            log.warning("missing cue \(cue.rawValue).wav — run tools/make_sfx.py")
            return nil
        }
        guard let player = try? AVAudioPlayer(contentsOf: url) else { return nil }
        player.prepareToPlay()
        players[cue] = player
        return player
    }

    func play(_ cue: SoundCue) {
        guard !isMuted, let player = player(for: cue) else { return }
        player.currentTime = 0
        player.play()
    }

    /// Fire a cue after a delay, for scoring animation beats.
    func play(_ cue: SoundCue, after delay: TimeInterval) {
        guard !isMuted else { return }
        Task { @MainActor in
            try? await Task.sleep(for: .seconds(delay))
            play(cue)
        }
    }
}
